[project]
name = "rag-owu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.4.247",
    "ollama>=0.4.7",
    "openai>=1.60.2",
    "pydantic-ai>=0.0.21",
    "streamlit>=1.41.1",
    "supabase>=2.12.0",
]
